language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-26.1.0
    - android-26

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

script:
  - sudo ./gradlew clean build